# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/User/Documents/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Documents/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.dcp
set_property used_in_implementation false [get_files c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/i3c2.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/adau1761_configuraiton_data.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/i2s_data_interface.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/i2c.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/ADAU1761_interface.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/clocking.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/adau1761_izedboard.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/new/fifo_delay.vhd
  C:/Users/User/Documents/project_1/project_1.srcs/sources_1/imports/hdl/audio_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/User/Documents/project_1/project_1.srcs/constrs_1/zed_audio.xdc
set_property used_in_implementation false [get_files C:/Users/User/Documents/project_1/project_1.srcs/constrs_1/zed_audio.xdc]

read_xdc C:/Users/User/Documents/project_1/project_1.srcs/constrs_1/new/dbg.xdc
set_property used_in_implementation false [get_files C:/Users/User/Documents/project_1/project_1.srcs/constrs_1/new/dbg.xdc]


synth_design -top audio_top -part xc7z020clg484-1


write_checkpoint -force -noxdef audio_top.dcp

catch { report_utilization -file audio_top_utilization_synth.rpt -pb audio_top_utilization_synth.pb }
