# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/Xfir_HPF_128t_b16_Z700.xci
# IP: The module: 'Xfir_HPF_128t_b16_Z700' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xfir_HPF_128t_b16_Z700'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/Xfir_HPF_128t_b16_Z700_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xfir_HPF_128t_b16_Z700'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/Xfir_HPF_128t_b16_Z700.xci
# IP: The module: 'Xfir_HPF_128t_b16_Z700' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xfir_HPF_128t_b16_Z700'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/User/Documents/project_1/project_1.srcs/sources_1/ip/Xfir_HPF_128t_b16_Z700/Xfir_HPF_128t_b16_Z700_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xfir_HPF_128t_b16_Z700'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
